---
title: "Statistics Canada Census 2016 - Lunenburg County Demographics"
author: "Ahmed Hussin"
date: "`r format(Sys.time(), '%Y-%m-%d')` "
output:
  html_document:
    highlight: tango
    keep_md: yes
    number_sections: yes
    theme: united
    toc: yes
    toc_float: yes
    fig_width: 6
    fig_height: 5
    fig_caption: yes
  pdf_document:
    toc: yes
    fig_crop: no
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  warning = FALSE,
  error = FALSE,
  auotdep = TRUE,
  include = FALSE,
  cache = TRUE,
  tidy = TRUE,
  options(scipen=999)
  )
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}

rm(list = ls())

library(cancensus) # access, retrieve, and work with Census data
library(dplyr) # data manipulation
library(purrr) # recursive programming
library(tidyr) # reshaping data
library(sf) # spatial data and visualization
library(ggplot2) # visua
library(ggrepel) # for smarter labelling
library(hrbrthemes) # typographic theme elements
library(rmapzen) # vector tiles for maps
library(RColorBrewer)
library(stringr)

datasets <- data.frame(list_census_datasets(use_cache = TRUE, quiet = FALSE))
dataset <- "CA16" # Select StatsCanada 2016 database
regions_df <- data.frame(list_census_regions("CA16"))
vectors_df <- list_census_vectors("CA16")
vectors_df<-vectors_df[!(vectors_df$type=="Female" | vectors_df$type=="Male"),]


####################################
####################################
#####################################
# Function to plot
#####################################
####################################
###################################


plot.census <- function(var){
  
var1 = "v_CA16_"
var_id = paste(var1,var,sep="")
# retrieve sf dataframe
lunenburg <- get_census(dataset='CA16', regions=list(PR="1206"),
                        vectors=c(var= var_id), level='CSD', quiet = TRUE, 
                        geo_format = 'sf', labels = 'short')
# remove reserves and chester: 
lunenburg <- lunenburg[lunenburg$`Region Name` != "Gold River 21 (IRI)" & lunenburg$`Region Name` != "Pennal 19 (IRI)" 
                       & lunenburg$`Region Name` != "New Ross 20 (IRI)" & lunenburg$`Region Name` != "Chester (MD)", ]

# get name of vector to include in plot:
var_name <- vectors_df %>% filter(str_detect(vector, var_id))

# calculate and plot % based on total population
lunenburg <- lunenburg %>% select(name, var)
lunenburg.sum <- sum(lunenburg$var)
lunenburg$percent <- (lunenburg$var/lunenburg.sum)*100
lunenburg <-lunenburg %>% mutate(across(where(is.numeric), round, 1))

# plot
ggplot(data=lunenburg, aes(x= factor(name, level = c('Mahone Bay (T)','Lunenburg (T)','Bridgewater (T)','Lunenburg (MD)')), y=var, fill=as.factor(name))) +
        geom_bar(stat="identity",color="black",size=1) + # border around bars
        labs(title = stringr::str_wrap(var_name$details, 100))+
        coord_flip() +
        ylab("") +
        xlab("") +
        scale_fill_brewer(palette="Set3")+
        geom_text(aes(label=var), hjust=-0.1, color="black", size=3) + # value on bar
        theme_classic() +
        theme(legend.position = "none") + # legend off
        theme(text = element_text(size=13,face="bold")) + # axis font size
        theme(plot.title = element_text(color="black", size=10, face="bold.italic"))+ # title cfg=
        theme(plot.title = element_text(hjust = 0.35, vjust=2.12)) +
        ylim(0, (0.03*(max(lunenburg$var))+max(lunenburg$var)))

}


##############################
############################################################
##############################
############################################################
############################## Plot % change (used for % change from 2011 to 2016)
############################################################
##############################
############################################################

plot.pct.change <- function(var){

var1 = "v_CA16_"
var_id = paste(var1,var,sep="")
# retrieve sf dataframe
lunenburg <- get_census(dataset='CA16', regions=list(PR="1206"),
                        vectors=c(var= var_id), level='CSD', quiet = TRUE, 
                        geo_format = 'sf', labels = 'short')
# remove reserves and chester: 
lunenburg <- lunenburg[lunenburg$`Region Name` != "Gold River 21 (IRI)" & lunenburg$`Region Name` != "Pennal 19 (IRI)" 
                       & lunenburg$`Region Name` != "New Ross 20 (IRI)" & lunenburg$`Region Name` != "Chester (MD)", ]

# get name of vector to include in plot:
var_name <- vectors_df %>% filter(str_detect(vector, var_id))

# plot
ggplot(data=lunenburg, aes(x= factor(name, level = c('Mahone Bay (T)','Lunenburg (T)','Bridgewater (T)','Lunenburg (MD)')), y=var, fill=as.factor(name))) +
        geom_bar(stat="identity",color="black",size=1) + # border around bars
        labs(title = stringr::str_wrap(var_name$details, 100))+
        coord_flip() +
        ylab("") +
        xlab("") +
        scale_fill_brewer(palette="Set3")+
        geom_text(aes(label=var), hjust=-0.1, color="black", size=3) + # value on bar
        theme_classic() +
        theme(legend.position = "none") + # legend off
        theme(text = element_text(size=13,face="bold")) + # axis font size
        theme(plot.title = element_text(color="black", size=10, face="bold.italic"))+ # title cfg=
        theme(plot.title = element_text(hjust = 0.35, vjust=2.12)) 

}

##############################
############################################################
##############################
############################################################
############################## Plot as % of town's population
############################################################
##############################
############################################################

plot.census.percent.total <- function(var){
  
var1 = "v_CA16_"
var_id = paste(var1,var,sep="")
# retrieve sf dataframe
lunenburg <- get_census(dataset='CA16', regions=list(PR="1206"),
                        vectors=c(var= var_id), level='CSD', quiet = TRUE, 
                        geo_format = 'sf', labels = 'short')
# remove reserves and chester: 
lunenburg <- lunenburg[lunenburg$`Region Name` != "Gold River 21 (IRI)" & lunenburg$`Region Name` != "Pennal 19 (IRI)" 
                       & lunenburg$`Region Name` != "New Ross 20 (IRI)" & lunenburg$`Region Name` != "Chester (MD)", ]

# get name of vector to include in plot:
var_name <- vectors_df %>% filter(str_detect(vector, var_id))

# calculate and plot % based on total population
lunenburg$percent <- (lunenburg$var/lunenburg$Population)*100
lunenburg <-lunenburg %>% mutate(across(where(is.numeric), round, 1))

# plot
ggplot(data=lunenburg, aes(x= factor(name, level = c('Mahone Bay (T)','Lunenburg (T)','Bridgewater (T)','Lunenburg (MD)')), y=var, fill=as.factor(name))) +
        geom_bar(stat="identity",color="black",size=1) + # border around bars
        labs(title = stringr::str_wrap(var_name$details, 100))+
        coord_flip() +
        ylab("") +
        xlab("") +
        scale_fill_brewer(palette="Set3")+
        geom_text(aes(label=percent), hjust=-0.1, color="black", size=3) + # value on bar
        theme_classic() +
        theme(legend.position = "none") + # legend off
        theme(text = element_text(size=13,face="bold")) + # axis font size
        theme(plot.title = element_text(color="black", size=10, face="bold.italic"))+ # title cfg=
        theme(plot.title = element_text(hjust = 0.35, vjust=2.12)) +
        ylim(0, (0.03*(max(lunenburg$var))+max(lunenburg$var)))

}


#############################################################
#############################################################
#############################################################
#############################################################
#############################################################
################# Ethnic origin summary in HRM:
#############################################################
#############################################################
#############################################################
#############################################################
#############################################################

plot.census.hali <- function(var){
  
var1 = "v_CA16_"
var_id = paste(var1,var,sep="")
# retrieve sf dataframe
halifax <- get_census(dataset='CA16', regions=list(PR="1209"),
                        vectors=c(var= var_id), level='CD', quiet = TRUE, 
                        geo_format = 'sf', labels = 'short')

# get name of vector to include in plot:
var_name <- vectors_df %>% filter(str_detect(vector, var_id))

# calculate and plot % based on total population
halifax$percent <- (halifax$var/halifax$Population)*100
halifax <-halifax %>% mutate(across(where(is.numeric), round, 1))

# plot
ggplot(data=halifax, aes(x= factor(name, level = c('Halifax (CD)')), y=var, fill=as.factor(name))) +
        geom_bar(stat="identity",color="black",size=1) + # border around bars
        labs(title = stringr::str_wrap(var_name$details, 100))+
        coord_flip() +
        ylab("") +
        xlab("%") +
        scale_fill_brewer(palette="Set3")+
        geom_text(aes(label=var), hjust=-0.1, color="black", size=3) + # value on bar
        theme_classic() +
        theme(legend.position = "none") + # legend off
        theme(text = element_text(size=13,face="bold")) + # axis font size
        theme(plot.title = element_text(color="black", size=10, face="bold.italic"))+ # title cfg=
        theme(plot.title = element_text(hjust = 0.35, vjust=2.12)) +
        ylim(0, (0.03*(max(halifax$var))+max(halifax$var)))

}

```

# Overall
```{r echo=FALSE, include=TRUE, message=FALSE, fig.height=2.25, fig.width=8}
plot.census(401)
plot.census(402)
plot.pct.change(403) 

```

# Immigrant generation
```{r echo=FALSE, include=TRUE, message=FALSE, fig.height=2.25, fig.width=8}
plot.census.percent.total(3822)
plot.census.percent.total(3825)
plot.census.percent.total(3828)

```

# Ethnic origin
```{r echo=FALSE, include=TRUE, message=FALSE, fig.height=2.25, fig.width=8}
plot.census.percent.total(4044)
plot.census.percent.total(4014)


plot.census.percent.total(4002)
plot.census.percent.total(4266)
plot.census.percent.total(4329) # latin, central and south american
plot.census.percent.total(4404)

plot.census.percent.total(4611)
plot.census.percent.total(4698)
plot.census.percent.total(4743)
plot.census.percent.total(4806) # oceania

```

# Summary of ethnic groups in Lunenburg (MD)
```{r echo=FALSE, include=TRUE, message=FALSE, fig.height=3, fig.width=8}

df <- data.frame(name=c("South Asian","Caribbean","Central/South American","African","East/South-East Asian",
                        "West Asian/Middle Eastern","Aboriginal"),
                count=c(25,35,55,90,100,105,1570))

df$pct <- (df$count/24863)*100
df <-df %>% mutate(across(where(is.numeric), round, 1))

# 
# ggplot(data=df, aes(x=factor(name,level=c("South Asian","Caribbean","Oceanic","Central/South American","African","East/South-East Asian","West Asian/Middle Eastern","Aboriginal")), y=count, fill=as.factor(name))) + 
#         geom_bar(stat="identity",color="black",size=1)+
#         coord_flip() +
#         ylab("count") +
#         xlab("") +
#         scale_fill_brewer(palette="RdGy")+
#         geom_text(aes(label=count), hjust=-0.1, color="black", size=3.5) + # value on bar
#         theme_classic() +
#         theme(legend.position = "none") + # legend off
#         theme(text = element_text(size=15,face="bold"))+
#         ylim(0, 1650)



ggplot(data=df, aes(x=factor(name,level=c("South Asian","Caribbean","Central/South American","African","East/South-East Asian","West Asian/Middle Eastern","Aboriginal")), y=pct, fill=as.factor(name))) + 
        geom_bar(stat="identity",color="black",size=1)+
        coord_flip() +
        ylab("% of LMD Population") +
        xlab("") +
        scale_fill_brewer(palette="RdGy")+
        geom_text(aes(label=pct), hjust=-0.1, color="black", size=3.5) + # value on bar
        theme_classic() +
        theme(legend.position = "none") + # legend off
        theme(text = element_text(size=15,face="bold"))+
        ylim(0, 7)
# axis font size
```


# Summary of ethnic groups in Bridgewater
```{r echo=FALSE, include=TRUE, message=FALSE, fig.height=3, fig.width=8}

df <- data.frame(name=c("West Asian/Middle Eastern","African","Caribbean","Central/South American","South Asian",
                        "East/South-East Asian","Aboriginal"),
                count=c(20,30,30,35,90,115,580))

df$pct <- (df$count/8532)*100
df <-df %>% mutate(across(where(is.numeric), round, 1))


# ggplot(data=df, aes(x=factor(name,level=c("West Asian/Middle Eastern","African","Caribbean","Central/South American","South Asian",
#                         "East/South-East Asian","Aboriginal")), y=count, fill=as.factor(name))) + 
#         geom_bar(stat="identity",color="black",size=1)+
#         coord_flip() +
#         ylab("count") +
#         xlab("") +
#         scale_fill_brewer(palette="RdGy")+
#         geom_text(aes(label=count), hjust=-0.1, color="black", size=3.5) + # value on bar
#         theme_classic() +
#         theme(legend.position = "none") + # legend off
#         theme(text = element_text(size=15,face="bold"))+
#         ylim(0, 600)


ggplot(data=df, aes(x=factor(name,level=c("West Asian/Middle Eastern","African","Caribbean","Central/South American","South Asian",
                        "East/South-East Asian","Aboriginal")), y=pct, fill=as.factor(name))) + 
        geom_bar(stat="identity",color="black",size=1)+
        coord_flip() +
        ylab("% of Bridgewater Population") +
        xlab("") +
        scale_fill_brewer(palette="RdGy")+
        geom_text(aes(label=pct), hjust=-0.1, color="black", size=3.5) + # value on bar
        theme_classic() +
        theme(legend.position = "none") + # legend off
        theme(text = element_text(size=15,face="bold"))+
        ylim(0, 7)

```


# Summary of ethnic groups in HRM
```{r echo=FALSE, include=TRUE, message=FALSE, fig.height=3.5, fig.width=12}

df <- data.frame(name=c("Central/South American",
                        "Caribbean",
                        "South Asian",
                        "African",
                        "East/South-East Asian",
                        "West Central Asian/Middle Eastern",
                        "Aboriginal"),
                count=c(2060,
                        3570,
                        6880,
                        12515,
                        12855,
                        13800,
                        26725))

df$pct <- (df$count/403390)*100
df <-df %>% mutate(across(where(is.numeric), round, 1))


ggplot(data=df, aes(x=factor(name,level=c("West Central Asian/Middle Eastern","African","Caribbean","Central/South American","South Asian",
                        "East/South-East Asian","Aboriginal")), y=pct, fill=as.factor(name))) + 
        geom_bar(stat="identity",color="black",size=1)+
        coord_flip() +
        ylab("% of Halifax Population") +
        xlab("") +
        scale_fill_brewer(palette="RdGy")+
        geom_text(aes(label=pct), hjust=-0.1, color="black", size=4.5) + # value on bar
        theme_classic() +
        theme(legend.position = "none") + # legend off
        theme(text = element_text(size=19,face="bold"))+
        ylim(0, 7)

```












